[2021-08-08 02:03:22,758] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_suppliers 2021-08-08T02:03:21.100084+00:00 [queued]>
[2021-08-08 02:03:22,866] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_suppliers 2021-08-08T02:03:21.100084+00:00 [queued]>
[2021-08-08 02:03:22,868] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 02:03:22,870] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-08 02:03:22,871] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 02:03:22,911] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): create_standardized_table_suppliers> on 2021-08-08T02:03:21.100084+00:00
[2021-08-08 02:03:22,949] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'standardized_pipeline', 'create_standardized_table_suppliers', '2021-08-08T02:03:21.100084+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/standardized_pipeline.py', '--cfg-path', '/tmp/tmpiu8bc56v', '--error-file', '/tmp/tmp22wa1vaq']
[2021-08-08 02:03:22,955] {standard_task_runner.py:77} INFO - Job 21: Subtask create_standardized_table_suppliers
[2021-08-08 02:03:22,925] {standard_task_runner.py:52} INFO - Started process 3626 to run task
[2021-08-08 02:03:23,268] {logging_mixin.py:104} INFO - Running <TaskInstance: standardized_pipeline.create_standardized_table_suppliers 2021-08-08T02:03:21.100084+00:00 [running]> on host 02070657999c
[2021-08-08 02:03:23,561] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=standardized_pipeline
AIRFLOW_CTX_TASK_ID=create_standardized_table_suppliers
AIRFLOW_CTX_EXECUTION_DATE=2021-08-08T02:03:21.100084+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-08T02:03:21.100084+00:00
[2021-08-08 02:03:23,566] {mysql.py:70} INFO - Executing: CREATE TABLE IF NOT EXISTS suppliers AS
WITH data_last_5_minutes AS (
	SELECT
        DISTINCT
        CAST(S_SUPPKEY AS SIGNED) AS SUPPLIER_KEY,
        S_NAME AS SUPPLIER_NAME,
        S_ADDRESS AS SUPPLIER_ADDRESS,
        CAST(S_NATIONKEY AS SIGNED) AS NATION_KEY,
        S_PHONE AS SUPPLIER_PHONE,
        S_ACCTBAL AS SUPPLIER_ACCOUNT_BALANCE_TOTAL,
        S_COMMENT AS SUPPLIER_COMMENT
    FROM
        datalake.SUPPLIER
    WHERE 
        INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 5 MINUTE)
)

SELECT 
	* 
FROM 
	data_last_5_minutes
[2021-08-08 02:03:23,608] {base.py:78} INFO - Using connection to: id: dwh_id. Host: dwh, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-08-08 02:03:23,644] {dbapi.py:204} INFO - Running statement: CREATE TABLE IF NOT EXISTS suppliers AS
WITH data_last_5_minutes AS (
	SELECT
        DISTINCT
        CAST(S_SUPPKEY AS SIGNED) AS SUPPLIER_KEY,
        S_NAME AS SUPPLIER_NAME,
        S_ADDRESS AS SUPPLIER_ADDRESS,
        CAST(S_NATIONKEY AS SIGNED) AS NATION_KEY,
        S_PHONE AS SUPPLIER_PHONE,
        S_ACCTBAL AS SUPPLIER_ACCOUNT_BALANCE_TOTAL,
        S_COMMENT AS SUPPLIER_COMMENT
    FROM
        datalake.SUPPLIER
    WHERE 
        INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 5 MINUTE)
)

SELECT 
	* 
FROM 
	data_last_5_minutes, parameters: None
[2021-08-08 02:03:23,649] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/operators/mysql.py", line 72, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1046, 'No database selected')
[2021-08-08 02:03:23,660] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=standardized_pipeline, task_id=create_standardized_table_suppliers, execution_date=20210808T020321, start_date=20210808T020322, end_date=20210808T020323
[2021-08-08 02:03:23,770] {local_task_job.py:149} INFO - Task exited with return code 1
