[2021-08-08 02:11:53,887] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_parts 2021-08-08T02:05:00+00:00 [queued]>
[2021-08-08 02:11:53,994] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_parts 2021-08-08T02:05:00+00:00 [queued]>
[2021-08-08 02:11:53,997] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 02:11:53,999] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-08 02:11:54,002] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 02:11:54,024] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): create_standardized_table_parts> on 2021-08-08T02:05:00+00:00
[2021-08-08 02:11:54,040] {standard_task_runner.py:52} INFO - Started process 206 to run task
[2021-08-08 02:11:54,068] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'standardized_pipeline', 'create_standardized_table_parts', '2021-08-08T02:05:00+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/standardized_pipeline.py', '--cfg-path', '/tmp/tmp8bx0laok', '--error-file', '/tmp/tmpt42gxmm9']
[2021-08-08 02:11:54,072] {standard_task_runner.py:77} INFO - Job 5: Subtask create_standardized_table_parts
[2021-08-08 02:11:54,318] {logging_mixin.py:104} INFO - Running <TaskInstance: standardized_pipeline.create_standardized_table_parts 2021-08-08T02:05:00+00:00 [running]> on host d995c427c378
[2021-08-08 02:11:54,704] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=standardized_pipeline
AIRFLOW_CTX_TASK_ID=create_standardized_table_parts
AIRFLOW_CTX_EXECUTION_DATE=2021-08-08T02:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-08T02:05:00+00:00
[2021-08-08 02:11:54,711] {mysql.py:70} INFO - Executing: CREATE TABLE IF NOT EXISTS standardized.parts AS
WITH data_last_5_minutes AS (
	SELECT
        DISTINCT
        CAST(P_PARTKEY AS SIGNED) AS PART_KEY,
        P_NAME AS PART_NAME,
        P_MFGR AS PART_MANUFACTURE_GROUP_NAME,
        P_BRAND AS PART_BRAND_NAME,
        P_TYPE AS PART_TYPE,
        CAST(P_SIZE AS SIGNED) AS PART_SIZE_NUMBER,
        P_CONTAINER AS PART_CONTAINER_TYPE,
        P_RETAILPRICE AS PART_RETAIL_PRICE,
        P_COMMENT AS PART_COMMENT,
        NOW() AS INGESTION_TIMESTAMP
    FROM
        datalake.PART
    WHERE 
        INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 5 MINUTE)
)

SELECT 
	* 
FROM 
	data_last_5_minutes
[2021-08-08 02:11:54,805] {base.py:78} INFO - Using connection to: id: dwh_id. Host: dwh, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-08-08 02:11:54,848] {dbapi.py:204} INFO - Running statement: CREATE TABLE IF NOT EXISTS standardized.parts AS
WITH data_last_5_minutes AS (
	SELECT
        DISTINCT
        CAST(P_PARTKEY AS SIGNED) AS PART_KEY,
        P_NAME AS PART_NAME,
        P_MFGR AS PART_MANUFACTURE_GROUP_NAME,
        P_BRAND AS PART_BRAND_NAME,
        P_TYPE AS PART_TYPE,
        CAST(P_SIZE AS SIGNED) AS PART_SIZE_NUMBER,
        P_CONTAINER AS PART_CONTAINER_TYPE,
        P_RETAILPRICE AS PART_RETAIL_PRICE,
        P_COMMENT AS PART_COMMENT,
        NOW() AS INGESTION_TIMESTAMP
    FROM
        datalake.PART
    WHERE 
        INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 5 MINUTE)
)

SELECT 
	* 
FROM 
	data_last_5_minutes, parameters: None
[2021-08-08 02:11:54,862] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/operators/mysql.py", line 72, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1067, "Invalid default value for 'INGESTION_TIMESTAMP'")
[2021-08-08 02:11:54,883] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=standardized_pipeline, task_id=create_standardized_table_parts, execution_date=20210808T020500, start_date=20210808T021153, end_date=20210808T021154
[2021-08-08 02:11:55,077] {local_task_job.py:149} INFO - Task exited with return code 1
