[2021-08-07 14:10:03,833] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_supplier 2021-08-07T14:05:00+00:00 [queued]>
[2021-08-07 14:10:03,843] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_supplier 2021-08-07T14:05:00+00:00 [queued]>
[2021-08-07 14:10:03,844] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 14:10:03,844] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-07 14:10:03,845] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 14:10:03,857] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): create_standardized_table_supplier> on 2021-08-07T14:05:00+00:00
[2021-08-07 14:10:03,865] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'standardized_pipeline', 'create_standardized_table_supplier', '2021-08-07T14:05:00+00:00', '--job-id', '28', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/standardized_pipeline.py', '--cfg-path', '/tmp/tmpr_e0jrb1', '--error-file', '/tmp/tmplfnsal7j']
[2021-08-07 14:10:03,861] {standard_task_runner.py:52} INFO - Started process 3616 to run task
[2021-08-07 14:10:03,866] {standard_task_runner.py:77} INFO - Job 28: Subtask create_standardized_table_supplier
[2021-08-07 14:10:03,910] {logging_mixin.py:104} INFO - Running <TaskInstance: standardized_pipeline.create_standardized_table_supplier 2021-08-07T14:05:00+00:00 [running]> on host ab70d6dafbc6
[2021-08-07 14:10:03,959] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=standardized_pipeline
AIRFLOW_CTX_TASK_ID=create_standardized_table_supplier
AIRFLOW_CTX_EXECUTION_DATE=2021-08-07T14:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-07T14:05:00+00:00
[2021-08-07 14:10:03,960] {mysql.py:70} INFO - Executing: CREATE TABLE IF NOT EXISTS standardized.SUPPLIER (
  `SUPPLIER_KEY` int NOT NULL,
  `SUPPLIER_NAME` text NOT NULL,
  `SUPPLIER_ADDRESS` text NOT NULL,
  `NATION_KEY` int NOT NULL,
  `SUPPLIER_PHONE` text NOT NULL,
  `SUPPLIER_ACCTBAL` int NOT NULL,
  `SUPPLIER_COMMENT` text NOT NULL,
  `INGESTION_TIMESTAMP` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SUPPLIER_SUPPKEY`),
  KEY `NATION_KEY` (`NATION_KEY`),
  CONSTRAINT `SUPPLIER_ibfk_1` FOREIGN KEY (`NATION_KEY`) REFERENCES `NATION` (`NATION_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
[2021-08-07 14:10:03,969] {base.py:78} INFO - Using connection to: id: dwh_id. Host: dwh, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-08-07 14:10:03,979] {dbapi.py:204} INFO - Running statement: CREATE TABLE IF NOT EXISTS standardized.SUPPLIER (
  `SUPPLIER_KEY` int NOT NULL,
  `SUPPLIER_NAME` text NOT NULL,
  `SUPPLIER_ADDRESS` text NOT NULL,
  `NATION_KEY` int NOT NULL,
  `SUPPLIER_PHONE` text NOT NULL,
  `SUPPLIER_ACCTBAL` int NOT NULL,
  `SUPPLIER_COMMENT` text NOT NULL,
  `INGESTION_TIMESTAMP` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SUPPLIER_SUPPKEY`),
  KEY `NATION_KEY` (`NATION_KEY`),
  CONSTRAINT `SUPPLIER_ibfk_1` FOREIGN KEY (`NATION_KEY`) REFERENCES `NATION` (`NATION_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;, parameters: None
[2021-08-07 14:10:03,981] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/operators/mysql.py", line 72, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1072, "Key column 'SUPPLIER_SUPPKEY' doesn't exist in table")
[2021-08-07 14:10:03,984] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=standardized_pipeline, task_id=create_standardized_table_supplier, execution_date=20210807T140500, start_date=20210807T141003, end_date=20210807T141003
[2021-08-07 14:10:04,042] {local_task_job.py:149} INFO - Task exited with return code 1
