[2021-08-08 05:11:03,721] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: to_datalake_pipeline.extract_from_git 2021-08-08T05:05:00+00:00 [queued]>
[2021-08-08 05:11:03,748] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: to_datalake_pipeline.extract_from_git 2021-08-08T05:05:00+00:00 [queued]>
[2021-08-08 05:11:03,749] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 05:11:03,750] {taskinstance.py:1088} INFO - Starting attempt 2 of 11
[2021-08-08 05:11:03,750] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 05:11:03,760] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): extract_from_git> on 2021-08-08T05:05:00+00:00
[2021-08-08 05:11:03,772] {standard_task_runner.py:52} INFO - Started process 275 to run task
[2021-08-08 05:11:03,779] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'to_datalake_pipeline', 'extract_from_git', '2021-08-08T05:05:00+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/to_datalake_pipeline.py', '--cfg-path', '/tmp/tmp3zmqznrw', '--error-file', '/tmp/tmpo86vz0wi']
[2021-08-08 05:11:03,781] {standard_task_runner.py:77} INFO - Job 9: Subtask extract_from_git
[2021-08-08 05:11:03,844] {logging_mixin.py:104} INFO - Running <TaskInstance: to_datalake_pipeline.extract_from_git 2021-08-08T05:05:00+00:00 [running]> on host dbfb9e13da58
[2021-08-08 05:11:03,911] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=wildangbudhi@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=to_datalake_pipeline
AIRFLOW_CTX_TASK_ID=extract_from_git
AIRFLOW_CTX_EXECUTION_DATE=2021-08-08T05:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-08T05:05:00+00:00
[2021-08-08 05:11:03,914] {logging_mixin.py:104} INFO - Downloading data from -> https://raw.githubusercontent.com/rezaprimasatya/DTO-DE-JUN-MID/main/data.zip
[2021-08-08 05:11:04,709] {logging_mixin.py:104} INFO - Unzipping Data
[2021-08-08 05:11:04,816] {logging_mixin.py:104} INFO - Transform Data to Pandas Dataframe
[2021-08-08 05:11:05,111] {logging_mixin.py:104} INFO - Load data to datalake
[2021-08-08 05:11:05,166] {logging_mixin.py:104} INFO - Load table : REGION
[2021-08-08 05:11:05,219] {logging_mixin.py:104} INFO - Load table : NATION
[2021-08-08 05:11:05,243] {logging_mixin.py:104} INFO - Load table : PART
[2021-08-08 05:11:05,439] {logging_mixin.py:104} INFO - Load table : SUPPLIER
[2021-08-08 05:11:05,465] {logging_mixin.py:104} INFO - Load table : PARTSUPP
[2021-08-08 05:11:06,000] {logging_mixin.py:104} INFO - Load table : CUSTOMER
[2021-08-08 05:11:06,157] {logging_mixin.py:104} INFO - Load table : ORDERS
[2021-08-08 05:11:07,083] {logging_mixin.py:104} INFO - Load table : LINEITEM
[2021-08-08 05:11:13,803] {python.py:151} INFO - Done. Returned value was: None
[2021-08-08 05:11:13,818] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=to_datalake_pipeline, task_id=extract_from_git, execution_date=20210808T050500, start_date=20210808T051103, end_date=20210808T051113
[2021-08-08 05:11:13,860] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-08 05:11:13,889] {local_task_job.py:198} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-08-08 05:11:13,894] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 275
[2021-08-08 05:11:13,909] {process_utils.py:66} INFO - Process psutil.Process(pid=275, status='terminated', exitcode=0, started='05:11:03') (275) terminated with exit code 0
